openapi: 3.0.0
info:
  title: Documentación de la API de "la cuponera" seccion vendedores
  version: 1.0.0
paths:
  /api/vendedores:
    get:
      summary: Obtener todos los vendedores
      responses:
        '200':
          description: Éxito. Retorna una lista de vendedores
      responses:
        '200':
          description: Éxito. Retorna una lista de vendedores.
        '500':
          description: Error interno del servidor.
    post:
      summary: Crear un nuevo vendedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vendedor'
      responses:
        '201':
          description: vendedor creado correctamente.
        '500':
          description: Error interno del servidor.
  /api/vendedores/{id}:
    put:
      summary: Actualizar un vendedor existente
      parameters:
        - in: path
          name: id
          required: true
          description: ID del vendedor a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vendedor'
      responses:
        '200':
          description: vendedor actualizado correctamente.
        '404':
          description: vendedor no encontrado.
        '500':
          description: Error interno del servidor.
    delete:
      summary: Eliminar un vendedor existente
      parameters:
        - in: path
          name: id
          required: true
          description: ID del vendedor a eliminar
          schema:
            type: string
      responses:
        '200':
          description: vendedor eliminado correctamente.
        '404':
          description: vendedor no encontrado.
        '500':
          description: Error interno del servidor.
components:
  schemas:
    vendedor:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string

